---
title: "Homework 3"
date: 2024-06-08
format: html
author: "Rebecca-Jane Gullette
---
https://github.com/rebecca-jane-gullette/Gullette-RebeccaJane_homework-03.git

## Read in Packages and Data
```{r}
library(tidyverse) # clean data
library(readxl) # read in excel file 
library(here) # find file
library(janitor) # clean data
library(GGally) # data visualization 
library(MuMIn) # model selection
library(ggeffects) # model predictions
library(gtsummary) # summary tables
library(flextable) # flex tables
library(modelsummary) # model tables

drought_exp <- read_xlsx(path = here("data", # reading in data
                                     "Valliere_etal_EcoApps_Data.xlsx"),
                         sheet = "First Harvest")
```

# Problem 1

## a. code and annotations

```{r}
 modelsummary::modelsummary(
  list(
    "Null Model: No Predictors" = model0,
    "Model 1: All Predictors" = model1,
    "Model 2: SLA and Water Treatment" = model2,
    "Model 3: SLA and Species" = model3,
    "Model 4: Water Treatment and Species" = model4
  )
)
```

## b.


## c.  code and annotations


## d. 

## e. 







